language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "avsharapov-github"
script:
  # other script steps might be done before running the actual analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=${SONAR_TOKEN}